#!/bin/bash 
if [ -f $1 ]
then
        for i in $(cat $1|sed s'/.*\]//'g|sed s'/2018.*$//'g|grep '[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}')
        do
        {
	echo "$i";ping -c 3 -W 1 "$i"|egrep --colour '0%|100%'
        }
        done
else
        for l in $@
        do
	{
	echo "$l";ping -c 3 -W 1 "$l"|egrep --colour '0%|100%'
        }
        done
fi
